from app.models import *
from app.models.artist import *
from app.models.type import *
from app.models.show import *
from app.models.locality import *
from app.models.location import *
from app.models.user_profile import *
from app.models.collaboration import *
from app.models.artist_type import *
from app.models.representation import *
from app.models.representation_user import *