# Generated by Django 3.0.4 on 2020-04-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Artist_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type')),
            ],
            options={
                'verbose_name': 'Artist_type',
                'verbose_name_plural': 'Artist_types',
                'db_table': 'artist_type',
            },
        ),
    ]
