# Generated by Django 3.0.5 on 2020-04-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist_type',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='artist_type',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locality_id',
            new_name='locality',
        ),
    ]
