# Generated by Django 3.0.5 on 2020-04-14 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's profile",
                'verbose_name_plural': "User's profiles",
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='artist_type',
            table=None,
        ),
        migrations.AlterModelTable(
            name='collaboration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='locality',
            table=None,
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterModelTable(
            name='show',
            table=None,
        ),
        migrations.AlterModelTable(
            name='type',
            table=None,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
