# Generated by Django 3.0.4 on 2020-04-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['firstname', 'lastname', 'pk'], 'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
    ]
