# Generated by Django 3.0.5 on 2020-04-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200414_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.IntegerField()),
                ('show_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Locality')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.UserProfile')),
            ],
            options={
                'verbose_name': 'RepresentationUser',
                'verbose_name_plural': 'RepresentationUsers',
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Location')),
                ('show_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Locality')),
            ],
            options={
                'verbose_name': 'Representation',
                'verbose_name_plural': 'Representations',
            },
        ),
    ]
