# Generated by Django 3.0.5 on 2020-04-24 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200423_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='when',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
