# Generated by Django 3.0.5 on 2020-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200503_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('EN', 'Anglais'), ('FR', 'Français'), ('NL', 'Néerlandais'), ('GE', 'Allemand'), ('SP', 'Espagnol'), ('IT', 'Italien'), ('PO', 'Portugais')], default='FR', max_length=2),
        ),
    ]
