# Generated by Django 3.0.4 on 2020-04-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type')),
            ],
            options={
                'verbose_name': 'Artist type',
                'verbose_name_plural': 'Artist types',
                'ordering': ['pk'],
            },
        ),
    ]
