# Generated by Django 3.0.5 on 2020-04-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_artisttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=6, unique=True)),
                ('locality', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['postal_code', 'locality', 'pk'],
            },
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
    ]
