# Generated by Django 3.0.5 on 2020-04-09 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200409_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['postal_code', 'locality', 'pk'], 'verbose_name': 'Locality', 'verbose_name_plural': 'Localities'},
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('designation', models.CharField(max_length=60)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('website', models.URLField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('locality_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Locality')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['pk'],
            },
        ),
    ]
