# Generated by Django 3.0.5 on 2020-04-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200409_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttype',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ArtistType')),
                ('showId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
                'ordering': ['pk'],
            },
        ),
    ]
