# Generated by Django 3.0.5 on 2020-04-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200409_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttype',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('language', models.BooleanField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['pk'],
            },
        ),
    ]
