# Generated by Django 3.0.5 on 2020-04-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_representation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='show_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Show'),
        ),
    ]
