# Generated by Django 3.0.5 on 2020-04-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200409_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttype',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('location_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
                ('show_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
            ],
            options={
                'verbose_name': 'Representation',
                'verbose_name_plural': 'Representations',
            },
        ),
    ]
