# Generated by Django 3.0.5 on 2020-04-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200412_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Locality'),
        ),
    ]
