# Generated by Django 3.0.5 on 2020-04-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200412_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representation_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Representation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile')),
            ],
            options={
                'verbose_name': 'Representation User',
                'verbose_name_plural': 'Representation Users',
            },
        ),
    ]
