# Generated by Django 3.0.5 on 2020-04-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_representation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist_type',
            options={'verbose_name': 'Artist Type', 'verbose_name_plural': 'Artist Types'},
        ),
    ]
