# Generated by Django 3.0.5 on 2020-04-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200412_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='location',
        ),
        migrations.AddField(
            model_name='representation',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
    ]
