# Generated by Django 3.0.5 on 2020-04-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200412_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
    ]
