# Generated by Django 3.0.5 on 2020-04-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200421_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representation',
            old_name='when',
            new_name='time',
        ),
        migrations.AddField(
            model_name='representation',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='representation',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
    ]
