# Generated by Django 3.0.5 on 2020-04-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200412_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist_type',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='artist_type',
            old_name='type',
            new_name='type_id',
        ),
    ]
