# Generated by Django 3.0.5 on 2020-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200412_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(max_length=255),
        ),
    ]
