# Generated by Django 3.0.5 on 2020-04-21 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200421_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['types', 'pk'], 'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.RenameField(
            model_name='type',
            old_name='expertise',
            new_name='types',
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='artistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
    ]
