# Generated by Django 3.0.5 on 2020-04-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200412_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='bookable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
