# Generated by Django 3.0.5 on 2020-04-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200412_1700'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table=None,
        ),
    ]
