# Generated by Django 3.0.5 on 2020-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200412_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
    ]
