# Generated by Django 3.0.5 on 2020-04-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200412_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
    ]
