from app.admin.artist import *
from app.admin.artist_type import *
from app.admin.collaboration import *
from app.admin.locality import *
from app.admin.location import *
from app.admin.role import *
from app.admin.show import *
from app.admin.type import *
from app.admin.user_profile import *
from app.admin.representation import *